import LeftPanel from "../../components/LeftPanel";
import styles from "../../styles/LoginRegister.module.css";

import React from "react";
import Head from "next/head";
import Link from "next/link";

const Login = () => {
	return (
		<>
			<Head>
				<title>Login</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/Logo.png" />
			</Head>
			<div className="container-fluid row">
				<LeftPanel />
				<div className="col">
					<div className="position-relative top-50 translate-middle-y col-11 ps-5">
						<div>
							<p className={`my-3 fs-1 ${styles.helo}`}>Halo, Pewpeople</p>
							<p className={`${styles.subHelo}`}>
								Selamat datang di Peworld, silahkan login untuk melanjutkan
							</p>
						</div>
						<Link href={"/login/user"}>
							<button className="col-12 btn btn-primary">
								Login akun pekerja
							</button>
						</Link>
						<div className="border my-4"></div>
						<Link href={"/login/recruiter"}>
							<button className="col-12 btn btn-primary mb-4">
								Login akun perekrut
							</button>
						</Link>
					</div>
				</div>
			</div>
		</>
	);
};

export default Login;
