import React from "react";
import LeftPanel from "../../components/LeftPanel";
import Head from "next/head";
import styles from "../../styles/LoginRegister.module.css";
import Link from "next/link";

const ResetPassword = () => {
	return (
		<>
			<Head>
				<title>Reset Password</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/Logo.png" />
			</Head>
			<div className="container-fluid row">
				<LeftPanel />
				<div className="col pt-5">
					<div className="position-relative col-11 ps-5 pt-5">
						<div>
							<p className={`my-3 fs-1 ${styles.helo}`}>Reset Password</p>
							<p className={`${styles.subHelo}`}>
								Enter your user accounts verified email address and we will send
								you a password reset link.
							</p>
						</div>
						<div className="pt-5">
							<form>
								<div className="mb-5">
									<label for="exampleInputEmail1" className="form-label">
										Email
									</label>
									<input
										type="email"
										className={`form-control ${styles.input}`}
										id="exampleInputEmail1"
										aria-describedby="emailHelp"
										placeholder="Masukan alamat email"
									/>
								</div>
								<div className="mb-4">
									<button type="submit" className={`col-12 ${styles.buttons}`}>
										Send password reset email
									</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</>
	);
};

export default ResetPassword;
