import React from "react";
import LeftPanel from "../../../components/LeftPanel";
import Head from "next/head";
import styles from "../../../styles/LoginRegister.module.css";
import Link from "next/link";

const UserLogin = () => {
	return (
		<>
			<Head>
				<title>Login</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/Logo.png" />
			</Head>
			<div className="container-fluid row">
				<LeftPanel />
				<div className="col pt-5">
					<div className="position-relative col-11 ps-5 pt-5">
						<div>
							<p className={`my-3 fs-2 ${styles.helo}`}>
								Please login with your account
							</p>
							<p className={`${styles.subHelo}`}>
								We have an an email containing a password reset instruction
								toyour email. please check your email.
							</p>
						</div>
						<div className="pt-5">
							<form>
								<div className="mb-4">
									<label for="exampleInputEmail1" className="form-label">
										Email
									</label>
									<input
										type="email"
										className={`form-control ${styles.input}`}
										id="exampleInputEmail1"
										aria-describedby="emailHelp"
										placeholder="Masukan alamat email"
									/>
								</div>
								<div className="mb-4">
									<label for="exampleInputPassword1" className="form-label">
										Password
									</label>
									<input
										type="password"
										className={`form-control ${styles.input}`}
										id="exampleInputPassword1"
										placeholder="Masukan password"
									/>
								</div>
								<div className="mb-4">
									<button type="submit" className={`col-12 ${styles.buttons}`}>
										Reset password
									</button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</>
	);
};

export default UserLogin;
