import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Landing.module.css";

export default function Landing() {
	return (
		<>
			<Head>
				<title>Welcome to Peworld</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/Logo.png" />
			</Head>
			<div className="container-fluid row mt-5">
				<section className="position-relative row justify-content-center align-items-center col-md-12 my-5">
					<div className="col-md-5">
						<h2 className={`${styles.title} pb-2`}>
							Talenta terbaik negri
							<br />
							untuk perubahan
							<br />
							revolusi 4.0
						</h2>
						<p className={`${styles.description} pb-4`}>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
							euismod ipsum et dui rhoncus auctor.
						</p>
						<button className={`${styles.buttons}`}>Mulai Dari Sekarang</button>
					</div>
					<div className="col-auto"></div>
					<div className={`col-md-4 ${styles.sect1}`}>
						<Image
							src={"/backgroundLogin.png"}
							width={400}
							height={400}
							alt=""
							className={`position-absolute top-0 ${styles.layer1}`}
						/>
						<Image
							src="/Layer3Sec1.png"
							width={500}
							height={500}
							alt=""
							className={`position-absolute top-0 ${styles.layer2}`}
						/>
						<Image
							src="/KotakUngu.png"
							width={95}
							height={95}
							alt=""
							className={`position-absolute ${styles.layer3}`}
						/>
						<Image
							src="/KotakKuning.png"
							width={40}
							height={40}
							alt=""
							className={`position-absolute ${styles.layer4}`}
						/>
					</div>
				</section>
				<section
					className={`position-relative row justify-content-center align-items-center col-md-12 ${styles.section2}`}>
					<div className="col-md-6">
						<Image
							src={"/GambarSect2.png"}
							width={450}
							height={380}
							alt=""
							className={`position-absolute top-0 ${styles.layer1sect2}`}
						/>
						<Image
							src="/Layer3Sect2.png"
							width={560}
							height={480}
							alt=""
							className={`position-absolute top-0 ${styles.layer2sect2}`}
						/>
						<Image
							src="/KotakUngu.png"
							width={80}
							height={80}
							alt=""
							className={`position-absolute ${styles.layer3sect2}`}
						/>
					</div>
					{/* <div className="col-auto"></div> */}
					<div className="col-md-5">
						<h2 className={`${styles.title} pb-2`}>
							Kenapa harus mencari talent
							<br />
							di peworld
						</h2>
						<ul className={`${styles.description} mt-3`}>
							<li className={`${styles.list} row my-3`}>
								<div className="col-auto">
									<Image src="/tick1.png" width={20} height={20} alt="" />
								</div>
								<p className={`col-auto`}>Lorem ipsum dolor sit amet.</p>
							</li>
							<li className={`${styles.list} row mb-3`}>
								<div className="col-auto">
									<Image src="/tick1.png" width={20} height={20} alt="" />
								</div>
								<p className={`col-auto`}>Lorem ipsum dolor sit amet.</p>
							</li>
							<li className={`${styles.list} row mb-3`}>
								<div className="col-auto">
									<Image src="/tick1.png" width={20} height={20} alt="" />
								</div>
								<p className={`col-auto`}>Lorem ipsum dolor sit amet.</p>
							</li>
							<li className={`${styles.list} row`}>
								<div className="col-auto">
									<Image src="/tick1.png" width={20} height={20} alt="" />
								</div>
								<p className={`col-auto`}>Lorem ipsum dolor sit amet.</p>
							</li>
						</ul>
					</div>
				</section>
				<section
					className={`position-relative row justify-content-center align-items-center col-md-12 ${styles.section3}`}>
					<div className="col-md-5">
						<h2 className={`${styles.title} pb-2`}>Skill Talent</h2>
						<p className={`${styles.description} pb-4`}>
							Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
							euismod ipsum et dui rhoncus auctor.
						</p>
						<div className="row ms-3">
							<ul className={`${styles.description} me-5 col-auto`}>
								<li className={`${styles.list} row my-3`}>
									<div className="col-auto">
										<Image src="/tick13.png" width={20} height={20} alt="" />
									</div>
									<p className={`col-auto`}>Java</p>
								</li>
								<li className={`${styles.list} row mb-3`}>
									<div className="col-auto">
										<Image src="/tick13.png" width={20} height={20} alt="" />
									</div>
									<p className={`col-auto`}>Kotlin</p>
								</li>
								<li className={`${styles.list} row mb-3`}>
									<div className="col-auto">
										<Image src="/tick13.png" width={20} height={20} alt="" />
									</div>
									<p className={`col-auto`}>PHP</p>
								</li>
								<li className={`${styles.list} row`}>
									<div className="col-auto">
										<Image src="/tick13.png" width={20} height={20} alt="" />
									</div>
									<p className={`col-auto`}>JavaScript</p>
								</li>
							</ul>
							<ul
								className={`${styles.description} ${styles.list2} col-auto ms-5`}>
								<li className={`${styles.list} row my-3`}>
									<div className="col-auto">
										<Image src="/tick13.png" width={20} height={20} alt="" />
									</div>
									<p className={`col-auto`}>Golang</p>
								</li>
								<li className={`${styles.list} row mb-3`}>
									<div className="col-auto">
										<Image src="/tick13.png" width={20} height={20} alt="" />
									</div>
									<p className={`col-auto`}>C++</p>
								</li>
								<li className={`${styles.list} row mb-3`}>
									<div className="col-auto">
										<Image src="/tick13.png" width={20} height={20} alt="" />
									</div>
									<p className={`col-auto`}>Ruby</p>
								</li>
								<li className={`${styles.list} row`}>
									<div className="col-auto">
										<Image src="/tick13.png" width={20} height={20} alt="" />
									</div>
									<p className={`col-auto`}>10+ Bahasa Lainnya</p>
								</li>
							</ul>
						</div>
					</div>
					<div className="col-auto"></div>
					<div className="col-md-4">
						<Image
							src={"/GambarSect3.png"}
							width={450}
							height={380}
							alt=""
							className={`position-absolute top-0 ${styles.layer1sect3}`}
						/>
						<Image
							src="/Layer3Sec1.png"
							width={560}
							height={480}
							alt=""
							className={`position-absolute top-0 ${styles.layer2sect3}`}
						/>
						<Image
							src="/KotakKuning.png"
							width={80}
							height={80}
							alt=""
							className={`position-absolute ${styles.layer4sect3}`}
						/>
					</div>
				</section>
				<section className={`text-center ${styles.section4}`}>
					<h2 className={`${styles.title} mb-5`}>
						Their opinion about Peworld
					</h2>
					<div
						className={`d-flex justify-content-center align-items-center ${styles.cardsSect}`}>
						<div
							className={`card ${styles.cards} mx-3`}
							style={{ width: "18rem" }}>
							<Image
								src="/avatar.png"
								className={`${styles.cardImage} mx-auto d-block mt-4`}
								alt="..."
								width={110}
								height={110}
							/>
							<div className="card-body">
								<h4 className={`${styles.titleCard}`}>Louis Tomlinson</h4>
								<p className={`${styles.subsCard}`}>Web Developer</p>
								<p className="card-text">
									Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
									euismod ipsum et dui rhoncus auctor.
								</p>
							</div>
						</div>
						<div
							className={`card ${styles.cards} mx-3`}
							style={{ width: "18rem" }}>
							<Image
								src="/avatar.png"
								className={`${styles.cardImage} mx-auto d-block mt-4`}
								alt="..."
								width={110}
								height={110}
							/>
							<div className="card-body">
								<h4 className={`${styles.titleCard}`}>Louis Tomlinson</h4>
								<p className={`${styles.subsCard}`}>Web Developer</p>
								<p className="card-text">
									Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
									euismod ipsum et dui rhoncus auctor.
								</p>
							</div>
						</div>
						<div
							className={`card ${styles.cards} mx-3`}
							style={{ width: "18rem" }}>
							<Image
								src="/avatar.png"
								className={`${styles.cardImage} mx-auto d-block mt-4`}
								alt="..."
								width={110}
								height={110}
							/>
							<div className="card-body">
								<h4 className={`${styles.titleCard}`}>Louis Tomlinson</h4>
								<p className={`${styles.subsCard}`}>Web Developer</p>
								<p className="card-text">
									Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
									euismod ipsum et dui rhoncus auctor.
								</p>
							</div>
						</div>
					</div>
				</section>
				<section className="container-fluid row my-5">
					<div className={`${styles.startNow} col-10 row my-5`}>
						<div className="row">
							<Image
								src="/LayerStarting.png"
								height={167}
								width={940}
								alt=""
								className={`position-absolute start-50 translate-middle-x col-md-7 ${styles.bgStart}`}
							/>
							<Image
								src="/Vector41.png"
								height={167}
								width={940}
								alt=""
								className={`position-absolute start-50 translate-middle-x col-md-7 ${styles.bgStart}`}
							/>
						</div>
						<div className="row">
							<h2 className={`${styles.titleStart} col-md-4 position-relative`}>
								Lorem ipsum
								<br />
								dolor sit amet
							</h2>
							<div className="col-md-10"></div>
							<button
								className={`col-2 position-relative bottom-50 ${styles.startNowBtn}`}>
								Mulai Dari Sekarang
							</button>
						</div>
					</div>
				</section>
			</div>
		</>
	);
}
Landing.layout = "L1";
