import React, { useState } from "react";
import LeftPanel from "../../../components/LeftPanel";
import Head from "next/head";
import styles from "../../../styles/LoginRegister.module.css";
import Link from "next/link";
import { useRouter } from "next/router";
import axios from "axios";

const UserLogin = () => {
	const router = useRouter();

	const [form, setForm] = useState({
		email: "",
		password: "",
	});

	const onSubmit = (e) => {
		e.preventDefault();

		axios
			.post(`${process.env.NEXT_PUBLIC_BACKEND_URL}/user/login`, form)
			.then((response) => {
				console.log(response);
				alert("Login success");
				localStorage.setItem("token", response.data.data.token);
				localStorage.setItem("data", JSON.stringify(response.data.data.data));
				return router.push("/home");
			})
			.catch((error) => {
				console.log(error);
				alert("Email atau password salah");
			});
	};

	return (
		<>
			<Head>
				<title>User Login</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/Logo.png" />
			</Head>
			<div className="container-fluid row">
				<LeftPanel />
				<div className="col pt-5">
					<div className="position-relative col-11 ps-5 pt-5">
						<div>
							<p className={`my-3 fs-1 ${styles.helo}`}>Halo, Pewpeople</p>
							<p className={`${styles.subHelo}`}>
								Lorem ipsum dolor sit amet, consectetur adipiscing elit. In
								euismod ipsum et dui rhoncus auctor.
							</p>
						</div>
						<div className="pt-5">
							<form onSubmit={(e) => onSubmit(e)}>
								<div className="mb-4">
									<label htmlFor="exampleInputEmail1" className="form-label">
										Email
									</label>
									<input
										type="email"
										className={`form-control ${styles.input}`}
										id="exampleInputEmail1"
										aria-describedby="emailHelp"
										placeholder="Masukan alamat email"
										onChange={(e) =>
											setForm({ ...form, email: e.target.value })
										}
									/>
								</div>
								<div className="mb-4">
									<label htmlFor="exampleInputPassword1" className="form-label">
										Password
									</label>
									<input
										type="password"
										className={`form-control ${styles.input}`}
										id="exampleInputPassword1"
										placeholder="Masukan password"
										onChange={(e) =>
											setForm({ ...form, password: e.target.value })
										}
									/>
								</div>
								<div className="mb-4">
									<Link
										href="#"
										className={`d-flex justify-content-end ${styles.link}`}>
										Lupa Kata Sandi
									</Link>
								</div>
								<div className="mb-4">
									<button type="submit" className={`col-12 ${styles.buttons}`}>
										Masuk
									</button>
								</div>
								<div className="mb-4">
									<p className="text-center">
										Anda belum punya akun?{" "}
										<span>
											<Link
												className={`${styles.link} ${styles.signLink}`}
												href="/register">
												Daftar disini
											</Link>
										</span>
									</p>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</>
	);
};

export default UserLogin;
